### ISSUE TITLE
Atiesh doesn't count

### ISSUE THREAD

**Issue by Sheed90** [Lexiebean/BetterCharacterStats#3]
Hey Lexie, unfortunately Atiesh doesn't count on addheal - only the aura counts:

![image](https://github.com/Lexiebean/BetterCharacterStats/assets/10332184/b27f89e6-8db2-4616-a195-6bb4008df653)
![image](https://github.com/Lexiebean/BetterCharacterStats/assets/10332184/8cae7d70-60cb-412d-90cf-13379d5c13e5)

Greetings
Sheed

**Comment by Ennea** [comment]
Here's the string for the equip effect:
`"Equip: Increases your spell damage by up to (%d+) and your healing by up to (%d+)."`

And here's the one for the description of the aura it gives, although for some reason that seems to be factored in already, and I do not know how/why:
`"Increases healing done by magical spells and effects by up to (%d+)."`
